[package]
name = "rabbit"
version = "0.1.0"
edition = "2021"
default-run = "rabbit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
clap = {version = "4.2.7", features = ["derive"]}
thiserror = "1.0.40"
